# Generated by Django 5.2 on 2025-05-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rds_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
