# Generated by Django 5.2 on 2025-05-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rds_app', '0002_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
