name: Deploy Django to EC2 (No Docker)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/app

          echo "Pulling latest code..."
          git pull origin main

          echo "Activating virtual environment..."
          source venv/bin/activate

          echo "Installing dependencies..."
          pip install -r requirements.txt

          echo "Running migrations..."
          python manage.py migrate


          echo "Restarting Gunicorn..."
          sudo systemctl restart gunicorn

          echo "Deployment complete."
        EOF
